home:
    path : /
    defaults: { _controller: FrameworkBundle:Template:template, template: ::base.html.twig }


api:
    resource: "@SensioApiBundle/Resources/config/routing.xml"
    prefix:   /api
